### ISSUE TITLE
Share Android Studio settings

### ISSUE THREAD

**Issue by gmacario** [WillyShakes/UdooWtf#14]
Interesting read to try solving the issue we faced at the droidconit Hackaton 2016:

https://medium.com/sebs-top-tips/share-the-settings-with-the-whole-team-android-studio-protip-6-3cce16eb2ea4

**Comment by WillyShakes** [comment]
Prova questo:
[settings.zip](https://github.com/WillyShakes/UdooWtf/files/219005/settings.zip)
